This XML file does not appear to have any style information associated with it. The document tree is shown below.
<!--  WSDL for arireg X-road v6  -->
<!--  Version: 0.10.4-live, tasuta, date 2021-07-28 10:52, by user ando  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:swa="http://ws-i.org/profiles/basic/1.1/xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd" xmlns:xid="http://x-road.eu/xsd/identifiers" xmlns:ar="http://arireg.x-road.eu/producer/" name="ariregv6API" targetNamespace="http://arireg.x-road.eu/producer/">
<wsdl:types>
<xsd:schema targetNamespace="http://arireg.x-road.eu/producer/" elementFormDefault="qualified">
<xsd:import namespace="http://x-road.eu/xsd/xroad.xsd" schemaLocation="http://x-road.eu/xsd/xroad.xsd"/>
<xsd:import namespace="http://ws-i.org/profiles/basic/1.1/xsd" schemaLocation="http://ws-i.org/profiles/basic/1.1/swaref.xsd"/>
<!--  debugAdapter_v1  -->

<!--  detailandmed_v1  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_detailandmed_v1.xsd"/>
<!--  detailandmed_v2  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_detailandmed_v2.xsd"/>
<!--  detailandmed_v3  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_detailandmed_v3.xsd"/>

<!--  lihtandmedTasuta_v1  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_lihtandmedTasuta_v1.xsd"/>
<!--  lihtandmed_v1  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_lihtandmed_v1.xsd"/>
<!--  lihtandmed_v2  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_lihtandmed_v2.xsd"/>
<!--  lihtandmed_v3  -->
<xsd:include schemaLocation="https://www2.rik.ee/schemas/xtee6/arireg/live/xroad6_lihtandmed_v3.xsd"/>
</xsd:schema>
</wsdl:types>

<!--  Messages for ARIREG  -->



<wsdl:message name="XroadHeaderMsg">
<wsdl:part name="client" element="xrd:client"/>
<wsdl:part name="service" element="xrd:service"/>
<wsdl:part name="id" element="xrd:id"/>
<wsdl:part name="userId" element="xrd:userId"/>
<wsdl:part name="protocolVersion" element="xrd:protocolVersion"/>
</wsdl:message>

<wsdl:message name="detailandmed_v1">
<wsdl:part name="detailandmed_v1" element="ar:detailandmed_v1"/>
</wsdl:message>
<wsdl:message name="detailandmed_v1Response">
<wsdl:part name="detailandmed_v1Response" element="ar:detailandmed_v1Response"/>
</wsdl:message>
<wsdl:message name="detailandmed_v2">
<wsdl:part name="detailandmed_v2" element="ar:detailandmed_v2"/>
</wsdl:message>
<wsdl:message name="detailandmed_v2Response">
<wsdl:part name="detailandmed_v2Response" element="ar:detailandmed_v2Response"/>
</wsdl:message>
<wsdl:message name="detailandmed_v3">
<wsdl:part name="detailandmed_v3" element="ar:detailandmed_v3"/>
</wsdl:message>
<wsdl:message name="detailandmed_v3Response">
<wsdl:part name="detailandmed_v3Response" element="ar:detailandmed_v3Response"/>
</wsdl:message>
<wsdl:message name="lihtandmedTasuta_v1">
<wsdl:part name="lihtandmedTasuta_v1" element="ar:lihtandmedTasuta_v1"/>
</wsdl:message>
<wsdl:message name="lihtandmedTasuta_v1Response">
<wsdl:part name="lihtandmedTasuta_v1Response" element="ar:lihtandmedTasuta_v1Response"/>
</wsdl:message>
<wsdl:message name="lihtandmed_v1">
<wsdl:part name="lihtandmed_v1" element="ar:lihtandmed_v1"/>
</wsdl:message>
<wsdl:message name="lihtandmed_v1Response">
<wsdl:part name="lihtandmed_v1Response" element="ar:lihtandmed_v1Response"/>
</wsdl:message>
<wsdl:message name="lihtandmed_v2">
<wsdl:part name="lihtandmed_v2" element="ar:lihtandmed_v2"/>
</wsdl:message>
<wsdl:message name="lihtandmed_v2Response">
<wsdl:part name="lihtandmed_v2Response" element="ar:lihtandmed_v2Response"/>
</wsdl:message>
<wsdl:message name="lihtandmed_v3">
<wsdl:part name="lihtandmed_v3" element="ar:lihtandmed_v3"/>
</wsdl:message>
<wsdl:message name="lihtandmed_v3Response">
<wsdl:part name="lihtandmed_v3Response" element="ar:lihtandmed_v3Response"/>
</wsdl:message>
<!--  Port for ARIREG  -->
<wsdl:portType name="AriregXtee">

<wsdl:operation name="detailandmed_v1" parameterOrder="detailandmed_v1">
<wsdl:documentation>
<xrd:title>Ettevõtja detailandmete päring</xrd:title>
</wsdl:documentation>
<wsdl:input name="detailandmed_v1" message="ar:detailandmed_v1"/>
<wsdl:output name="detailandmed_v1Response" message="ar:detailandmed_v1Response"/>
</wsdl:operation>
<wsdl:operation name="detailandmed_v2" parameterOrder="detailandmed_v2">
<wsdl:documentation>
<xrd:title>Ettevõtja detailandmete päring</xrd:title>
</wsdl:documentation>
<wsdl:input name="detailandmed_v2" message="ar:detailandmed_v2"/>
<wsdl:output name="detailandmed_v2Response" message="ar:detailandmed_v2Response"/>
</wsdl:operation>
<wsdl:operation name="detailandmed_v3" parameterOrder="detailandmed_v3">
<wsdl:documentation>
<xrd:title>Ettevõtja detailandmete päring</xrd:title>
</wsdl:documentation>
<wsdl:input name="detailandmed_v3" message="ar:detailandmed_v3"/>
<wsdl:output name="detailandmed_v3Response" message="ar:detailandmed_v3Response"/>
</wsdl:operation>



<wsdl:operation name="lihtandmedTasuta_v1" parameterOrder="lihtandmedTasuta_v1">
<wsdl:documentation>
<xrd:title>Ettevõtja lihtandmete päring tasuta</xrd:title>
</wsdl:documentation>
<wsdl:input name="lihtandmedTasuta_v1" message="ar:lihtandmedTasuta_v1"/>
<wsdl:output name="lihtandmedTasuta_v1Response" message="ar:lihtandmedTasuta_v1Response"/>
</wsdl:operation>
<wsdl:operation name="lihtandmed_v1" parameterOrder="lihtandmed_v1">
<wsdl:documentation>
<xrd:title>Ettevõtja lihtandmete päring</xrd:title>
</wsdl:documentation>
<wsdl:input name="lihtandmed_v1" message="ar:lihtandmed_v1"/>
<wsdl:output name="lihtandmed_v1Response" message="ar:lihtandmed_v1Response"/>
</wsdl:operation>
<wsdl:operation name="lihtandmed_v2" parameterOrder="lihtandmed_v2">
<wsdl:documentation>
<xrd:title>Ettevõtja lihtandmete päring</xrd:title>
</wsdl:documentation>
<wsdl:input name="lihtandmed_v2" message="ar:lihtandmed_v2"/>
<wsdl:output name="lihtandmed_v2Response" message="ar:lihtandmed_v2Response"/>
</wsdl:operation>
<wsdl:operation name="lihtandmed_v3" parameterOrder="lihtandmed_v3">
<wsdl:documentation>
<xrd:title>Ettevõtja lihtandmete päring</xrd:title>
</wsdl:documentation>
<wsdl:input name="lihtandmed_v3" message="ar:lihtandmed_v3"/>
<wsdl:output name="lihtandmed_v3Response" message="ar:lihtandmed_v3Response"/>
</wsdl:operation>




<wsdl:operation name="detailandmedEP_v1" parameterOrder="detailandmedEP_v1">
<wsdl:documentation>
<xrd:title>Ettevõtja detailandmete päring Eesti Pangale</xrd:title>
</wsdl:documentation>
<wsdl:input name="detailandmedEP_v1" message="ar:detailandmedEP_v1"/>
<wsdl:output name="detailandmedEP_v1Response" message="ar:detailandmedEP_v1Response"/>
</wsdl:operation>
</wsdl:portType>
<!--  Binding for ARIREG - document/literal wrapped, SOAP over HTTP  -->
<wsdl:binding name="AriregXtee" type="ar:AriregXtee">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>


<wsdl:operation name="detailandmed_v1">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="detailandmed_v1">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="detailandmed_v1Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="detailandmed_v2">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="detailandmed_v2">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="detailandmed_v2Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="detailandmed_v3">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="detailandmed_v3">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="detailandmed_v3Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>



<wsdl:operation name="lihtandmed_v1">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="lihtandmed_v1">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>

<wsdl:output name="lihtandmed_v1Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="lihtandmed_v2">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="lihtandmed_v2">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="lihtandmed_v2Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>

<wsdl:operation name="lihtandmed_v3">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="lihtandmed_v3">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="lihtandmed_v3Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>




<wsdl:operation name="detailandmedEP_v1">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="detailandmedEP_v1">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="detailandmedEP_v1Response">
<mime:multipartRelated>
<mime:part name="bodyWithAttachments">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</mime:part>
</mime:multipartRelated>
</wsdl:output>
</wsdl:operation>



<wsdl:operation name="earveRegistriParing_v1">
<soap:operation soapAction="" style="document"/>
<xrd:version>v1</xrd:version>
<wsdl:input name="earveRegistriParing_v1">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:input>
<wsdl:output name="earveRegistriParing_v1Response">
<soap:body use="literal"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="client"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="service"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="id"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="userId"/>
<soap:header use="literal" message="ar:XroadHeaderMsg" part="protocolVersion"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<!--  Endpoint for ARIREG  -->
<wsdl:service name="arireg">
<wsdl:port binding="ar:AriregXtee" name="AriregXtee">
<soap:address location="http://example.org/xroad-endpoint"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
